### ISSUE TITLE
Do we really need a dedicated maven plugin?

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-maven-plugin#3]
Some time ago a nice gist was created by @nochmu
https://gist.github.com/nochmu/1f640b01a685f3f83a349de2db8a8882
It was originally referenced in: utPLSQL/utPLSQL#508

The gist shows how to integrate `utPSLQL-cli` as a maven goal in one of maven phases.
It uses `exec-maven-plugin`.

I'm wondering if there is anything extra that we need/can achieve with a dedicated maven plugin for utPLSQL or should we just use the gist as a template for integrating utPLSQL with maven and don't bother creating a dedicated solution.

The benefit of not having yet another maven plugin is that we are much more nimble and the project is kept relatively lightweight.

As the project grows it becomes harder to maintain and harder to develop without breaking any dependencies. 

Keeping it light is, in my opinion, one of the key factors to successful future of project and it's growth.

My biggest fear is that at some point we might reach scale, were it will be too costly to change.

**Comment by pesse** [comment]
I agree with the concerns. It's hard enough to keep the essential parts healthy and high Quality

**Comment by nochmu** [comment]
I want a Maven plugin. Why? 
Although my Gist works quite well so far, it has a disadvantage: 
It is not independent from the environment. 
See line 12: Either you have to include the CLI in the code or you have to adjust the path. If you're developing on Linux and Windows same time, it's really annoying.   A Maven plugin could provide (reuse) the CLI and would be independent from the environment. 

Line 28-41: is very ugly because you have to create the output directory if it does not exist. Maybe it can be fixed in the cli. 

I think it's not necessary that the plugin can do more than the cli. However, it could simplify the configuration.

**Comment by jgebal** [comment]
We already gave the plugin a go.
If you're capable of helping out on it we welcome hands willing
